name: ARGO CICD WORKFLOW

on:
  push:
    branches: [master]

jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/} | sed "s/\\//-/g")" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repo_name=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')" >> $GITHUB_OUTPUT  

      - name: Another step
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"
          echo "Repo: ${{ steps.vars.outputs.repo_name }}"

      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mohitv1/argocd-project:${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          registry: docker.io
          pushImage: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          
      - name: Update image in deployment.yaml
        run: |
          git pull
          IMAGE_NAME="mohitv1/argocd-project:${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}"
          sed -i "s|image:.*|image: $IMAGE_NAME|g" ./manifests/deployment.yaml

      - name: Commit changes
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add ./manifests/deployment.yaml
          git commit -m "Update container image in deployment.yaml"
          git push
      
